#!/usr/bin/env python3
"""
gen_overrides.py — emit C implementations for the matchmaking-family
flat-C exports that route through OUR libsteamclient.so instead of
gbe_fork's emulator state.

The hybrid bridge forwards ~1200 SteamAPI calls to gbe_fork
(via PE export forwards in steam_api_bridge.def), but matchmaking
exports are carved out as direct exports of our bridge. Game-side
calls to e.g. SteamAPI_ISteamMatchmaking_RequestLobbyList land in
this file's implementations.

Routing strategy:
  1. Each override lazily acquires OUR ISteamMatchmaking pointer by
     LoadLibrary("steamclient64.dll") + GetProcAddress("CreateInterface")
     + CreateInterface("SteamClient020") to get ISteamClient*, then
     calling its vtable[10] (GetISteamMatchmaking) to get the
     matchmaking interface. lsteamclient.dll wraps our libsteamclient.so's
     ISteamMatchmakingStub, so the returned pointer's vtable layout
     matches the SDK (and matches our isteam_stubs.cpp's virtual
     declaration order).
  2. The override IGNORES the `self` arg (which would be gbe_fork's
     matchmaking pointer if the game even passed it). It dispatches
     via OUR cached pointer's vtable at slot N — slot N is extracted
     from the existing steam_api_bridge_flat.c forwarder body, so
     gen_overrides + gen_forwarders stay in sync as the source class
     evolves.
  3. Per-call diagnostic logging to C:\\wnb.log via wnb_log_once stays
     in place — first invocation logged once per export.

If a specific call's vtable[N] dispatch crashes (the failure mode we
hit with the full-vtable bridge), the crash is ISOLATED to that
matchmaking method — the game's other Steam API calls continue
working via gbe_fork forwards.

Input:
  steam_api_bridge_flat.c — source of the vtable-slot numbers + the
  exact signatures.

Output:
  steam_api_bridge_overrides.c — one C function per matchmaking
  export, routing through OUR libsteamclient.so via cached
  ISteamMatchmaking pointer.
"""

from __future__ import annotations
import re
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent / "steam_api_bridge_flat.c"
OUT = Path(__file__).resolve().parent / "steam_api_bridge_overrides.c"

OVERRIDE_PREFIXES = (
    "SteamAPI_ISteamMatchmaking_",
    "SteamAPI_ISteamMatchmakingServers_",
)

# Extract the full forwarder body so we can lift the slot number from
# the existing flat-C output. The flat.c shape is:
#   WN_STEAMAPI_EXPORT <ret> <name>(void* self[, params]) {
#       if (self == NULL) return <X>;
#       void** vt = *(void***)self;
#       typedef <ret> (*Fn)(void*[, params]);
#       (return ?)((Fn)vt[N])(self[, args]);
#   }
FUNC_RE = re.compile(
    r"WN_STEAMAPI_EXPORT\s+(?P<ret>[A-Za-z0-9_*\s]+?)\s+"
    r"(?P<name>SteamAPI_[A-Za-z0-9_]+)\s*"
    r"\((?P<params>[^)]*)\)\s*\{"
    r"(?P<body>.*?)"
    r"\}\s*\n",
    re.DOTALL,
)
SLOT_RE = re.compile(r"vt\[(\d+)\]")


def default_ret(ret: str) -> str:
    ret = ret.strip()
    if ret == "void":
        return ""
    if ret == "void*":
        return "    return NULL;"
    return "    return 0;"


# Map override-prefix to the SDK interface version we ask for via
# CreateInterface, plus the ISteamClient vtable slot that returns it.
# The slot numbers come from our isteam_client.cpp's ISteamClientImpl:
#   slot 10 = GetISteamMatchmaking(int hUser, int hPipe, const char* ver)
#   slot 11 = GetISteamMatchmakingServers(int hUser, int hPipe, const char* ver)
INTERFACE_CONFIG = {
    "SteamAPI_ISteamMatchmaking_": {
        "version": "SteamMatchMaking009",
        "vtable_slot": 10,
        "cache_var": "g_our_matchmaking",
    },
    "SteamAPI_ISteamMatchmakingServers_": {
        "version": "SteamMatchMakingServers002",
        "vtable_slot": 11,
        "cache_var": "g_our_matchmaking_servers",
    },
}


PROLOGUE = r"""/* AUTO-GENERATED by gen_overrides.py — DO NOT EDIT. */

#include <windows.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

#define WN_STEAMAPI_EXPORT __declspec(dllexport)

/* Per-export first-call logger. Appends one line per unique override
 * to C:\\wnb.log on first invocation. Bounded by the size of the
 * once_names array; matchmaking exports are well under 64 even with
 * both families combined. */
static void wnb_log_once(const char* name) {
    static const char* once_names[64];
    static int once_count = 0;
    for (int i = 0; i < once_count; ++i) {
        if (once_names[i] == name) return;
    }
    if (once_count < 64) {
        once_names[once_count++] = name;
    }
    FILE* f = fopen("C:\\wnb.log", "a");
    if (f) {
        fputs(name, f);
        fputc('\n', f);
        fclose(f);
    }
}

/* CreateInterface-from-steamclient64.dll lazy resolver. Cached as a
 * function pointer so subsequent get_our_*() calls don't re-do the
 * LoadLibrary/GetProcAddress dance. */
typedef void* (*CreateInterface_fn)(const char* pchVersion, int* pCode);
static CreateInterface_fn g_create_interface = NULL;
static void* g_steam_client = NULL;
/* Valve steamclient64.dll module handle — kept so the callback pump
 * can resolve Steam_BGetCallback / Steam_FreeLastCallback /
 * Steam_GetAPICallResult from the SAME module the ISteamClient came
 * from. */
static HMODULE g_steamclient_module = NULL;

/* Valve flat-C callback-pump exports. SteamAPI_RunCallbacks normally
 * pumps the game's pipe via these; our bridge has to do it explicitly
 * for the Steam Launcher Valve pipe because the game's RunCallbacks lands on
 * gbe_fork (which only knows gbe's queue). Without this pump, async
 * results — RequestLobbyList -> LobbyMatchList_t,
 * RequestInternetServerList -> server rows — never reach the game and
 * the server browser stays empty even though the request reached
 * Valve's CMs. */
/* Return type is `unsigned char` not `int`: Valve's MSVC-built DLL
 * returns `bool` in AL only — reading EAX as int can pick up garbage
 * in the upper 3 bytes and make a false read non-zero. */
typedef unsigned char (*Steam_BGetCallback_fn)(int hpipe, void* pmsg);
typedef void          (*Steam_FreeLastCallback_fn)(int hpipe);
typedef unsigned char (*Steam_GetAPICallResult_fn)(int hpipe,
                                          unsigned long long hcall,
                                          void* pcb, int cb,
                                          int icb_expected,
                                          unsigned char* pbfailed);
static Steam_BGetCallback_fn      g_steam_bgetcallback     = NULL;
static Steam_FreeLastCallback_fn  g_steam_freelastcallback = NULL;
static Steam_GetAPICallResult_fn  g_steam_getapicallresult = NULL;

/* Dispatch entry points defined in steam_api_bridge_callbacks.c — fan
 * a drained callback / call-result out to the game's CCallback /
 * CCallResult listeners registered through our RegisterCallback
 * overrides. */
extern void wnb_dispatch_callback(int iCallback, const void* data, size_t data_size);
extern void wnb_dispatch_call_result(unsigned long long hAPICall, int io_failure,
                                     const void* data, size_t data_size);
/* Real pipe/user handles obtained from Valve's ISteamClient. Steam Launcher
 * runs Valve's REAL Windows steamclient64.dll, which (unlike our old
 * libsteamclient.so) does NOT accept the placeholder 1,1 — it routes
 * GetISteam* dispatch through the pipe/user, so a bogus handle yields
 * a NULL or inert interface and matchmaking silently returns nothing.
 * 0 = not yet acquired. */
static int g_steam_pipe = 0;
static int g_steam_user = 0;

extern void wnb_publish_dispatch_pointers(void);

static void wnb_resolver_log(const char* msg) {
    FILE* f = fopen("C:\\wnb.log", "a");
    if (f) { fputs(msg, f); fputc('\n', f); fclose(f); }
}

static void* resolve_steam_client(void) {
    if (g_steam_client != NULL) return g_steam_client;
    /* Publish our callback-dispatch function pointers to a known file
     * so cm_bridge.cpp (in libwnsteam.so) can invoke them when a
     * cross-process IPC lobby response arrives. Same wine process,
     * raw addresses are valid. See steam_api_bridge_callbacks.c.
     *
     * Steam Launcher: `steamclient64.dll` in the wine prefix is now Valve's
     * REAL 25 MB Windows DLL (staged from valve-steam-x86_64.tzst),
     * NOT the Proton lsteamclient forwarder. Wine's lsteamclient.dll
     * bridge is deleted from system32 by the Steam Launcher scrub in
     * XServerDisplayActivity, so LoadLibrary("steamclient64.dll")
     * here resolves to Valve's real binary — same one wn-steam-
     * launcher.exe loaded in its sibling process. Valve's in-Wine
     * named-object IPC links the two so this client process talks
     * to the launcher's logged-in Steam session. */
    wnb_publish_dispatch_pointers();
    /* Load Valve's REAL steamclient64.dll by FULL PATH. A bare
     * LoadLibrary("steamclient64.dll") resolves to gbe_fork's stub
     * steamclient64.dll that sits in the game directory (the app dir
     * is searched before anything else), so the matchmaking routing
     * would hook gbe -> gbe and the Internet server browser stays
     * empty — and gbe's steamclient lacks the Steam_* pump exports.
     * SetDllDirectory + the full path + LOAD_WITH_ALTERED_SEARCH_PATH
     * mirrors how wn-steam-launcher.exe loads it. SetDllDirectory is
     * REQUIRED, not optional: steamclient64.dll imports from tier0_s64.dll
     * and vstdlib_s64.dll (objdump-confirmed), and without the Steam dir
     * on the DLL search path the game process cannot find them —
     * steamclient64.dll's tier0 imports (V_vsnprintf etc.) then stub
     * out (Wine attributes the stubs to ntdll) and process_attach
     * crashes with a page fault. LOAD_WITH_ALTERED_SEARCH_PATH alone
     * does NOT cover the transitive dependency search under Wine. */
    SetDllDirectoryA("C:\\Program Files (x86)\\Steam");
    HMODULE sc = LoadLibraryExA(
            "C:\\Program Files (x86)\\Steam\\steamclient64.dll",
            NULL, LOAD_WITH_ALTERED_SEARCH_PATH);
    if (sc == NULL) {
        wnb_resolver_log("[wnb] LoadLibraryEx(Valve steamclient64.dll) "
                         "failed — falling back to bare name (gbe stub)");
        sc = LoadLibraryA("steamclient64.dll");
    }
    if (sc == NULL) {
        wnb_resolver_log("[wnb] LoadLibrary(steamclient64.dll) failed");
        return NULL;
    }
    g_steamclient_module = sc;
    if (g_create_interface == NULL) {
        g_create_interface = (CreateInterface_fn)GetProcAddress(sc, "CreateInterface");
        if (g_create_interface == NULL) {
            wnb_resolver_log("[wnb] steamclient64.dll missing CreateInterface");
            return NULL;
        }
    }
    /* Resolve the flat-C callback-pump exports from the SAME module.
     * wnb_pump_valve_callbacks() (called by SteamAPI_RunCallbacks)
     * uses these to drain Valve's pipe. */
    g_steam_bgetcallback = (Steam_BGetCallback_fn)
            GetProcAddress(sc, "Steam_BGetCallback");
    g_steam_freelastcallback = (Steam_FreeLastCallback_fn)
            GetProcAddress(sc, "Steam_FreeLastCallback");
    g_steam_getapicallresult = (Steam_GetAPICallResult_fn)
            GetProcAddress(sc, "Steam_GetAPICallResult");
    {
        char buf[160];
        snprintf(buf, sizeof(buf),
                 "[wnb] callback-pump exports: BGetCallback=%p "
                 "FreeLastCallback=%p GetAPICallResult=%p",
                 (void*)g_steam_bgetcallback,
                 (void*)g_steam_freelastcallback,
                 (void*)g_steam_getapicallresult);
        wnb_resolver_log(buf);
    }
    int code = 0;
    g_steam_client = g_create_interface("SteamClient020", &code);
    if (g_steam_client == NULL) g_steam_client = g_create_interface("SteamClient019", &code);
    if (g_steam_client == NULL) g_steam_client = g_create_interface("SteamClient017", &code);
    if (g_steam_client == NULL) {
        wnb_resolver_log("[wnb] CreateInterface(SteamClient0XX) returned NULL");
        return NULL;
    }

    /* Acquire REAL pipe + user handles from Valve's ISteamClient.
     * Standard Steamworks client-process bootstrap (what every game's
     * own steam_api64.dll does internally):
     *   vt[0] CreateSteamPipe()          -> HSteamPipe
     *   vt[2] ConnectToGlobalUser(pipe)  -> HSteamUser
     * Valve's steamclient64.dll connects these to the global Steam
     * session that wn-steam-launcher.exe (our sibling steam.exe)
     * already created + logged on, via Valve's `\BaseNamedObjects\
     * STEAM_*` IPC. Without real handles, GetISteamMatchmaking on
     * Valve's real DLL returns an inert interface and the lobby /
     * server-browser list stays empty. */
    {
        void** vt = *(void***)g_steam_client;
        typedef int (*CreateSteamPipe_fn)(void*);
        typedef int (*ConnectToGlobalUser_fn)(void*, int);
        g_steam_pipe = ((CreateSteamPipe_fn)vt[0])(g_steam_client);
        if (g_steam_pipe != 0) {
            g_steam_user = ((ConnectToGlobalUser_fn)vt[2])(
                    g_steam_client, g_steam_pipe);
        }
        char buf[128];
        snprintf(buf, sizeof(buf),
                 "[wnb] Valve ISteamClient: pipe=%d user=%d",
                 g_steam_pipe, g_steam_user);
        wnb_resolver_log(buf);
        if (g_steam_pipe == 0 || g_steam_user == 0) {
            /* Fall back to 1,1 — better than 0,0; some Valve builds
             * accept the implicit global pipe. Logged so a failed
             * IPC handshake is diagnosable. */
            wnb_resolver_log("[wnb] WARNING: pipe/user handshake failed; "
                             "falling back to 1,1 (matchmaking may be empty)");
            if (g_steam_pipe == 0) g_steam_pipe = 1;
            if (g_steam_user == 0) g_steam_user = 1;
        }
    }
    return g_steam_client;
}

/* Per-interface lazy resolver — invoke a slot on the cached
 * ISteamClient* to get the requested interface pointer. The slot
 * numbers correspond to Valve's ISteamClient vtable:
 *   slot 10 GetISteamMatchmaking(hUser, hPipe, version)
 *   slot 11 GetISteamMatchmakingServers(hUser, hPipe, version)
 * Uses the REAL pipe/user acquired in resolve_steam_client().
 * Returns NULL on failure; overrides fall back to safe defaults in
 * that case. */
static void* resolve_interface(int slot, const char* version) {
    void* client = resolve_steam_client();
    if (client == NULL) return NULL;
    void** vt = *(void***)client;
    typedef void* (*GetIface_fn)(void*, int, int, const char*);
    void* iface = ((GetIface_fn)vt[slot])(
            client, g_steam_user, g_steam_pipe, version);
    char buf[128];
    snprintf(buf, sizeof(buf),
             "[wnb] resolve_interface slot=%d ver=%s pipe=%d user=%d -> %p",
             slot, version, g_steam_pipe, g_steam_user, iface);
    wnb_resolver_log(buf);
    return iface;
}

/* ── Steam Launcher: Valve callback pump ──────────────────────────────────────
 *
 * Drains Valve's real steamclient64.dll callback queue on OUR pipe
 * (g_steam_pipe, created in resolve_steam_client) and fans each event
 * out to the game's CCallback / CCallResult listeners.
 *
 * Why this is needed: the game's matchmaking flow is
 *   hCall = SteamMatchmaking()->RequestLobbyList();   // -> Valve CMs
 *   ... SteamAPI_RunCallbacks() ...                   // pump
 *   CCallResult<LobbyMatchList_t>::Run(...) fires      // result
 * The request reaches Valve (routing fix already verified), but the
 * RESULT comes back asynchronously as a callback on Valve's pipe.
 * The game's SteamAPI_RunCallbacks lands on gbe_fork, which only
 * pumps gbe's queue — so Valve's LobbyMatchList_t / server rows are
 * never delivered and the browser stays empty.
 *
 * SteamAPI_RunCallbacks (steam_api_bridge_callbacks.c) calls this
 * after pumping gbe.
 *
 * Steam's two callback kinds on the pipe:
 *  - Plain callback: iCallback != 703, m_pubParam is the struct.
 *    Dispatched straight to CCallback listeners.
 *  - Call-result completion: iCallback == 703 (SteamAPICallCompleted_t).
 *    m_pubParam is { uint64 hAsyncCall; int iCallback; uint32 cubParam }.
 *    We must then Steam_GetAPICallResult() to fetch the real payload
 *    and deliver it to the CCallResult keyed by hAsyncCall.
 */
void wnb_pump_valve_callbacks(void) {
    if (g_steam_client == NULL) return;          /* resolver not run yet */
    if (g_steam_bgetcallback == NULL || g_steam_freelastcallback == NULL) return;

    /* CallbackMsg_t (x64): { int32 hUser; int32 iCallback;
     *                        uint8* pubParam; int32 cubParam; } = 24 B */
    struct CallbackMsg { int hUser; int iCallback; void* pubParam; int cubParam; };
    struct CallbackMsg msg;
    int guard = 0;
    while (guard++ < 512 && g_steam_bgetcallback(g_steam_pipe, &msg)) {
        if (msg.iCallback == 703 /* SteamAPICallCompleted_t */) {
            /* SteamAPICallCompleted_t (x64):
             * { uint64 hAsyncCall; int32 iCallback; uint32 cubParam } */
            struct ApiCallDone {
                unsigned long long hAsyncCall;
                int      iCallback;
                unsigned cubParam;
            };
            if (msg.pubParam != NULL && g_steam_getapicallresult != NULL) {
                struct ApiCallDone cc = *(struct ApiCallDone*)msg.pubParam;
                unsigned char payload[2048];
                int sz = (int)(cc.cubParam < sizeof(payload)
                               ? cc.cubParam : sizeof(payload));
                unsigned char failed = 0;
                if (g_steam_getapicallresult(g_steam_pipe, cc.hAsyncCall,
                                             payload, sz, cc.iCallback,
                                             &failed)) {
                    char b[160];
                    snprintf(b, sizeof(b),
                             "[wnb] pump: call-result hCall=%llu cb=%d "
                             "sz=%d failed=%d -> dispatch",
                             cc.hAsyncCall, cc.iCallback, sz, failed);
                    wnb_resolver_log(b);
                    wnb_dispatch_call_result(cc.hAsyncCall, failed,
                                             payload, (size_t)sz);
                }
            }
        } else {
            char b[128];
            snprintf(b, sizeof(b),
                     "[wnb] pump: callback id=%d sz=%d -> dispatch",
                     msg.iCallback, msg.cubParam);
            wnb_resolver_log(b);
            wnb_dispatch_callback(msg.iCallback, msg.pubParam,
                                  (size_t)msg.cubParam);
        }
        g_steam_freelastcallback(g_steam_pipe);
    }
}

static void* g_our_matchmaking = NULL;
static void* g_our_matchmaking_servers = NULL;

/* Exposed (non-static) so steam_api_bridge_steamclient.c can use them
 * from its vtable hooks. Both files share the same resolver singleton:
 * the matchmaking pointer fetched via libsteamclient.so::CreateInterface
 * is cached here on first use, regardless of which entry point called. */
void* get_our_matchmaking(void) {
    if (g_our_matchmaking == NULL)
        g_our_matchmaking = resolve_interface(10, "SteamMatchMaking009");
    return g_our_matchmaking;
}

void* get_our_matchmaking_servers(void) {
    if (g_our_matchmaking_servers == NULL)
        g_our_matchmaking_servers = resolve_interface(11, "SteamMatchMakingServers002");
    return g_our_matchmaking_servers;
}

"""


def main() -> int:
    if not SRC.exists():
        print(f"ERROR: {SRC} missing — run gen_forwarders.py first", file=sys.stderr)
        return 1
    text = SRC.read_text(encoding="utf-8", errors="replace")

    out_lines = [PROLOGUE]
    count = 0
    for m in FUNC_RE.finditer(text):
        name = m.group("name")
        prefix = None
        for p in OVERRIDE_PREFIXES:
            if name.startswith(p):
                prefix = p
                break
        if prefix is None:
            continue
        ret = m.group("ret").strip()
        params = m.group("params").strip()
        body = m.group("body")
        slot_match = SLOT_RE.search(body)
        if not slot_match:
            print(f"WARNING: no vt[N] in {name}, skipping", file=sys.stderr)
            continue
        slot = int(slot_match.group(1))

        # Build the params-list-without-self for forwarding the args.
        # params text is like "void* self" or "void* self, int eLobbyType, ..."
        # Split by `,`, drop the first (self), strip names. Reassemble
        # types-only for the typedef + arg-names for the call.
        plist = [p.strip() for p in params.split(",")]
        if not plist or not plist[0].startswith("void* self"):
            print(f"WARNING: {name} first param isn't `void* self`, skipping", file=sys.stderr)
            continue
        extra = plist[1:]  # everything after self
        extra_types = []
        extra_names = []
        for i, p in enumerate(extra):
            # parse "<type> <name>" — last whitespace splits
            mm = re.match(r"(.*\S)\s+([A-Za-z_][A-Za-z0-9_]*)$", p)
            if mm:
                extra_types.append(mm.group(1).strip())
                extra_names.append(mm.group(2).strip())
            else:
                # No name — synthesize
                extra_types.append(p)
                extra_names.append(f"_a{i}")

        cfg = INTERFACE_CONFIG[prefix]
        getter = f"get_our_matchmaking()" if cfg["cache_var"] == "g_our_matchmaking" \
                 else f"get_our_matchmaking_servers()"

        # Build typedef
        if extra_types:
            typedef = f"{ret} (*Fn)(void*, {', '.join(extra_types)})"
            call_args = "mm, " + ", ".join(extra_names)
            param_str = "void* self, " + ", ".join(extra)
        else:
            typedef = f"{ret} (*Fn)(void*)"
            call_args = "mm"
            param_str = "void* self"

        out_lines.append(f"WN_STEAMAPI_EXPORT {ret} {name}({param_str}) {{")
        out_lines.append(f'    wnb_log_once("{name}");')
        out_lines.append(f"    (void)self;")
        out_lines.append(f"    void* mm = {getter};")
        if ret == "void":
            out_lines.append(f"    if (mm == NULL) return;")
        elif ret == "void*":
            out_lines.append(f"    if (mm == NULL) return NULL;")
        else:
            out_lines.append(f"    if (mm == NULL) return 0;")
        out_lines.append(f"    void** vt = *(void***)mm;")
        out_lines.append(f"    typedef {typedef};")
        prefix_ret = "" if ret == "void" else "return "
        out_lines.append(f"    {prefix_ret}((Fn)vt[{slot}])({call_args});")
        out_lines.append("}")
        out_lines.append("")
        count += 1

    OUT.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"[gen_overrides] {count} routed-override stubs → {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
